[dr]
type = drive
scope = drive
token = {"access_token":"ya29.a0AXooCgvfhPmSRlg0pbH5aAY9RBITvQC42grUWuD2QfxgZPyFPORfpMtesM9LWc-MtpHz5P7Rhvai2rE_wOKRMJA6ZEXd1H7gJrJhzntiyC46VwS20sZnIVTCoeXBVpuMnAtYRzC-rRxEPYVK8oiaxh1EaM_urxveOYXFaCgYKAdASARESFQHGX2Mi9VVb5henjMHmyAJtVUOZDQ0171","token_type":"Bearer","refresh_token":"1//0gtP8Al6o0uRKCgYIARAAGBASNwF-L9Irf2UnxO4Wo1gz6K7gIx6gjKhGmQcbjwv8u4tC2zOTFOpo-hYLBSnhnAXUwISi1pdUzkM","expiry":"2024-07-12T11:45:06.032504264+07:00"}
root_folder_id = 0AHM2dIhtjPQIUk9PVA
