[dr]
type = drive
scope = drive
token = {"access_token":"ya29.a0AXooCgvcq8GrGhm8lzBhBWqR7JsUvVc5MTk7YviyT_rRAE15CMyVhvp97bw6OKF2V6rOf6FZXdxj7Wfi6CHAS8ouadURI2Y1jmrCm5ksMREP9Xx_wGxei-DM3iq2BI1vD01oq-7KC6uxLCJszWl9x8NWgW_f-e_ciPtGaCgYKAYISARESFQHGX2MiSfPtm6vT0M2RBRYGhcvqew0171","token_type":"Bearer","refresh_token":"1//0g284iGhMN-rpCgYIARAAGBASNwF-L9IrDOj1hDE49uswzD8pBhilRCZSLSKtRCwY0i6heCfktZrV17IGyelV-q93iIIlhIBGCtw","expiry":"2024-07-12T11:14:54.11858834+07:00"}
root_folder_id = 0AHM2dIhtjPQIUk9PVA
