[dr]
type = drive
scope = drive
token = {"access_token":"ya29.a0AXooCgvr92eJecyc1ZMABHVWPAB-BEyDK9p8RCm0T3zK9Q1IRnY-tenSRYVI2snSvAcvORQf_wp6dSvU7UF_levMS9ZpMWA1LOGEfCTYGRH6-WcLPxefLJvGpI_Ri0LBoUr0Rsz1DmNW8yvIkOSbVdeiwVQWIyrs5LitFXUaCgYKAR4SARESFQHGX2Mi2FMpTPMVBms7JC4GuPBUDw0174","token_type":"Bearer","refresh_token":"1//0g5ypCWFJM6-WCgYIARAAGBASNwF-L9Irqk1lDEhUMNBrmAQ0VAO28UBh7zYMLs5Mixp0o-H0M21qhTPs07UROHRw5j7zKTr7PZk","expiry":"2024-07-06T09:31:20.84019029+07:00"}
root_folder_id = 0AHM2dIhtjPQIUk9PVA
